echo "... build start"
dir=$(cd $(dirname $0) && pwd)
cd ${dir}/../cmd/postman
go build -o ${dir}/../bin/mac/postman ./...
echo "completed ... mac"
GOOS=linux go build -o ${dir}/../bin/linux/64bit/postman ./...
echo "completed ... linux 64bit"
GOOS=linux GOARCH=386 go build -o ${dir}/../bin/linux/32bit/postman ./...
echo "completed ... linux 32bit"
GOOS=linux GOARCH=arm GOARM=6 go build -o ${dir}/../bin/linux/arm/armv6/postman ./...
echo "completed ... linux armv6"
GOOS=linux GOARCH=arm GOARM=7 go build -o ${dir}/../bin/linux/arm/armv7/postman ./...
echo "completed ... linux armv7"
echo "... and ./build.bat at windows"